show_excerpts: true

title: Calvin Huang
email: jibunhidoi999@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Calvin Huang's Personal Website
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://calvinh99.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: scholarc1314
github_username:  calvinh99

header_pages:
  - about.md
  - projects.md
  - resume-cv.md

collections:
  projects:
    output: true

# Build settings
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed

kramdown:
  auto_ids: true