title: Calvin Huang
email: jibunhidoi999@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Who I am and my projects.
baseurl: ""
url: "https://calvinh99.github.io"
twitter_username: ""
github_username:  calvinh99

# Build settings
theme: minima
plugins:
  - jekyll-feed
sass:
  sass_dir: _sass
  quiet_deps: true